### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by blerude** [JoBrigden/teacosy#5]
Grade: Meets Expectations

Awesome job on this project! You've included all the necessary elements here. Your code is very easy to read and follow due to your consistent formatting style and your use of comments. You have a great sense for ids and classes, how to apply them, and when to use which. Your CSS is also rock solid! 

Moving forward, pay attention to the tiny details. For example, make sure your containers hold all of the components that they should and make sure that your CSS code is properly aligned. Small oversights add up in coding, so you want to be very diligent. Also, feel free to take liberties in your CSS. Resources like Google Fonts, a font library, and Coolors.co, a color palette generator, can be useful in enhancing the visual aspect of your projects. Just some suggestions! Again, fantastic job here!

**Comment by JoBrigden** [comment]
Thanks for the feedback! :)
