### ISSUE TITLE
Subtle: Alignment

### ISSUE THREAD

**Issue by blerude** [JoBrigden/teacosy#6]
https://github.com/JoBrigden/teacosy/blob/master/resources/css/style.css#L63-L68
https://github.com/JoBrigden/teacosy/blob/master/resources/css/style.css#L26-L29

In these two cases, your alignment/indentation gets a bit sloppy. Be sure to stay consistent there!

**Comment by JoBrigden** [comment]
Geez, didn't even notice that, thanks.
